import type { Metadata } from "next";
import { poppins } from "@/app/ui/fonts"; 
import "./globals.css";
import Header from "@/app/ui/header";
import Footer from "@/app/ui/footer";

export const metadata: Metadata = {
  title: "Next Strix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className} >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
