const products = [
  {
    id: 1,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Alex Hunter",
    game: "Valorant",
    description:
      "Expert in aim improvement and strategy for competitive matches.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 2,
    image: "/assets/pexels-photo-7848986.webp",
    name: "GhostWolf",
    game: "Apex Legends",
    description:
      "Specialized in team coordination and advanced movement techniques.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 3,
    image: "/assets/pexels-photo-18269631.webp",
    name: "Sophia Blaze",
    game: "Rocket League",
    description:
      "Master aerial shots, rotations, and 1v1 mechanics like a pro.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 4,
    image: "/assets/pexels-photo-18305043.webp",
    name: "ViperX",
    game: "Valorant",
    description: "Learn map control, advanced utilities, and clutch scenarios.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 5,
    image: "/assets/pexels-photo-18271625.webp",
    name: "Leo Mastermind",
    game: "League of Legends",
    description: "Improve wave management, macro play, and decision-making.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 6,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Ava Predator",
    game: "Apex Legends",
    description:
      "Climb the ranks with expert-level tips on gunplay and tactics.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 7,
    image: "/assets/pexels-photo-18305043.webp",
    name: "ShadowAce",
    game: "Apex Legends",
    description:
      "Dominate the game with aggressive playstyle and perfect pushes.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 8,
    image: "/assets/pexels-photo-18347304.webp",
    name: "SkyBaller",
    game: "Rocket League",
    description:
      "Create opportunities and dominate the field with precise control.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 9,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "MaxSharp",
    game: "CS:GO",
    description:
      "Hone your aim, utility usage, and clutch instincts like a pro.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 10,
    image: "/assets/pexels-photo-18347304.webp",
    name: "Morgana Moves",
    game: "League of Legends",
    description:
      "Master your champions with optimized micro-mechanics and positioning.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 11,
    image: "/assets/pexels-photo-7848986.webp",
    name: "SniperElite",
    game: "CS:GO",
    description: "Improve team coordination and execute perfect strategies.",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
];

module.exports = {
  products,
};
