const products = [
  {
    id: 1,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 1",
    game: "Valorant",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 2,
    image: "/assets/pexels-photo-7848986.webp",
    name: "Coach 2",
    game: "Apex Legends",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 3,
    image: "/assets/pexels-photo-18269631.webp",
    name: "Coach 3",
    game: "Rocket League",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 4,
    image: "/assets/pexels-photo-18305043.webp",
    name: "Coach 4",
    game: "Valorant",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 5,
    image: "/assets/pexels-photo-18271625.webp",
    name: "Coach 5",
    game: "LoL",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 6,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 6",
    game: "Apex Legends",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 7,
    image: "/assets/pexels-photo-18305043.webp",
    name: "Coach 7",
    game: "Apex Legends",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 8,
    image: "/assets/pexels-photo-18347304.webp",
    name: "Coach 8",
    game: "Rocket League",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,

    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 9,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 9",
    game: "CS:GO",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 10,
    image: "/assets/pexels-photo-18347304.webp",
    name: "Coach 10",
    game: "LoL",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 11,
    image: "/assets/pexels-photo-7848986.webp",
    name: "Coach 11",
    game: "CS:GO",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,

    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 12,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 12",
    game: "CS:GO",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 13,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 13",
    game: "Apex Legends",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 14,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 14",
    game: "LoL",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 15,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 15",
    game: "Rocket League",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
  {
    id: 16,
    image: "/assets/pexels-yan-krukau-9072305.jpg",
    name: "Coach 16",
    game: "Valorant",
    description: "This is a description",
    lite_plan: 25,
    standard_plan: 75,
    extended_plan: 150,
    lite_stripe_price: "price_1OeyjYD72PzL52RmsTOTS5Xm",
    standard_stripe_price: "price_1OUQaHD72PzL52Rmb0u790EY",
    extended_stripe_price: "price_1OUQbID72PzL52RmWg7aDylo",
  },
];

module.exports = {
  products,
};
